---
title: "ag comments"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

-   Måtte fikse litt på .bib filen før dokumentet kjørte. Maskinene deres hadde hatt en liten krig om hvor filene var plassert lokalt på harddisken. Jeg kommer tilbake med mer info om strategi for hvordan en unngår dette (følg med på Canvas)
-   Endret til «sentence based line wrapping» (anbefales). Git liker best å jobbe med en og en linje. Settes i preferences under R Markdown \> Visuals \> Markdown.
-   Skrevet inn et forslag til en innledning. Bør være svært enkel. Hva dreier paperet seg om, hvordan har vi organisert det.
-   Har endret litt på bruk a sitering. Se hvordan in-line citation (dvs. uten rette klammer) og ikke inline (med rette klammer er brukt). Trenger ikke fortelle at det er en artikkel, tittel, årstall etc.. Det kan leseren finne selv i referansene.
-   Har også endret litt på nivået til overskriftene. Hvert avsnitt bør være heading 1 (har noe å bety når vi konverterer til andre format)

