---
title: "Can R Notebooks help with reproducibility?"
output:
  word_document: default
  html_document:
    df_print: paged
bibliography: reproducibility.bib
---

## Introduction

R Notebooks can help with reproducibility because ....

Barbara R.Jasny writes in an article that as new technologies produce
more and different data to work with the knowledge [@jasny_again_2011]

## Definition:

**R Notebook** is an R Markdown document with chunks that can be
executed independently and interactively, with output visible
immediately beneath the input @grolemund_r_nodate [***(skrevet rett av
og må fikses)***]{.ul}

Regarding to K. Bollen et al. in the national Science Foundation the
definitions for reproducibility, replicability and generalization is
clear:

**Reproducibility** means that a researcher have the opportunity to use
the result of a prior study and repeat the research with the same data
and procedures that were used in the orginal study. For the find to be
credible and informative that reproducibility is a minimum necessary
condition. @bollen_social_2015

**Replicability** is when a researcher follows the same procedures as in
an earlier study and manages to get the same result, but by collecting
new data. @bollen_social_2015

**Generalizability** refers to whether the result of a study apply in
other context or populations that differ from the original one
[***(skrevet rett av og må fikses)***]{.ul} @bollen_social_2015

## Benefits

As we have writtten about before, we use reproducibility to repeat a
research using the same data but with a separate twist.

Barbara R. Jasny et al. writes in an article that new technology is
constantly emerging, and produces new data in different variants, which
increases the expectations for new knowledge. [@jasny_again_2011]. By
increasing the expectations of the data, we can also see an increase in
the expectations for the content.

Although a test is reproducible, the quality may not be as good.

## Disadvantages

Steven N. Goodman et al. are writing in their article that
reproducibility, replicability, reliability, robustness, and
generalizability are used interchangeably in, for example, scientific
environments. The terms seem to be a confusion in the literature and it
can make it difficult to rely on a scientific result For their part, it
is mostly for use in the biomedical field, but there is great faith that
this could also solve other scientific areas.\@goodman_what_2016 An
example: Some groups believes reproducibility means repeating an
investigation in an article using the same data, and replicability means
doing it again, preferably with new data, but getting the same response.
While other groups believe the opposite.

There is also another minus with reproducibility and that is that the
result you have obtained can be built on by others who in turn can use
it to develop new ideas or other methods. It may lead to further errors
if the article was initially incorrect.

## Solution

First of all, a solution could be that the scientific enviroment came
together to create and definition to each of the different concepts
reproducibility, replicability, reliability, robustness, and
generalizability. It would have made the concepts easier to use and
which in turn had given a common understanding of what was used at any
given time. Steven N. Goodman et al. want to divide it into three
different elements: methods reproducibility, results reproducibility,
and inferential repro- ducibility. For their part, it is mostly for use
in the biomedical field, but there is great faith that this could also
solve other scientific areas.\@goodman_what_2016

## Referances

@goodman_what_2016

@bollen_social_2015

@jasny_again_2011

@grolemund_r_nodate
